### ISSUE TITLE
mongoerror: unsupported OP_QUERY command find

### ISSUE THREAD

**Issue by RaymondMeng** [symbench/electric-circuits#172]
![image](https://github.com/symbench/electric-circuits/assets/70761044/8008a3d9-efcf-4263-a241-5c776c0a6751)

**Comment by brollb** [comment]
This looks like a versioning issue with MongoDB and the adapter used by the version of WebGME (underlying framework for model-integrated computing). Can you try running MongoDB v5 via docker (as shown below)? I am not sure off hand the exact versioning constraints for MongoDB but version 5 should work.
```
docker run -d --network host mongo:5
```

Then start the server as before and see if you see the same error logs.

**note**: Running the database in docker is fine but you will want to mount the data volume (`/data/db` in the container) on the host file system or use a docker volume. Otherwise, your data will be lost when the container is removed.
